### ISSUE TITLE
obsolete routine usage

### ISSUE THREAD

**Issue by abzcoding** [arvancloud/arvannginx#4]
https://github.com/arvancloud/arvannginx/blob/75d4611310fb254130abd95f3b48f90c068a8a77/src/os/unix/ngx_process_cycle.c#L626

This C routine is considered [obsolete](http://man7.org/linux/man-pages/man3/usleep.3.html#CONFORMING_TO). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified. Use nanosleep(2) or setitimer(2) instead.

**Comment by smesgary** [comment]
Thanks, I'll consider it.
